steps:
  - name: node:12
    entrypoint: yarn
    args: ["install"]
  - name: node:12
    env:
      - "BUILD=$BUILD_ID"
      - "PROJECT=$PROJECT_ID"
      - "COMMIT=$SHORT_SHA"
      - "NEXT_PUBLIC_BUILDER_API_KEY=$_BUILDER_KEY"
    entrypoint: yarn
    args: ["run", "static-out"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./out", "gs://$_DESTINATION"]